/** Nombres en español por código ISO; fallback al nombre de Odoo si no hay entrada. */
const COUNTRY_NAMES_ES: Record<string, string> = {
  AD: "Andorra",
  AE: "Emiratos Árabes Unidos",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BE: "Bélgica",
  BG: "Bulgaria",
  BR: "Brasil",
  CA: "Canadá",
  CH: "Suiza",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CZ: "Chequia",
  DE: "Alemania",
  DK: "Dinamarca",
  DO: "República Dominicana",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egipto",
  ES: "España",
  FI: "Finlandia",
  FR: "Francia",
  GB: "Reino Unido",
  GR: "Grecia",
  GT: "Guatemala",
  HN: "Honduras",
  HR: "Croacia",
  HU: "Hungría",
  IE: "Irlanda",
  IL: "Israel",
  IN: "India",
  IS: "Islandia",
  IT: "Italia",
  JP: "Japón",
  LU: "Luxemburgo",
  MA: "Marruecos",
  MX: "México",
  NI: "Nicaragua",
  NL: "Países Bajos",
  NO: "Noruega",
  PA: "Panamá",
  PE: "Perú",
  PL: "Polonia",
  PT: "Portugal",
  PY: "Paraguay",
  RO: "Rumanía",
  RS: "Serbia",
  RU: "Rusia",
  SE: "Suecia",
  SV: "El Salvador",
  TR: "Turquía",
  UA: "Ucrania",
  US: "Estados Unidos",
  UY: "Uruguay",
  VE: "Venezuela",
}

export function getCountryDisplayName(code: string, fallbackName: string): string {
  const normalized = code.trim().toUpperCase()
  if (normalized && COUNTRY_NAMES_ES[normalized]) {
    return COUNTRY_NAMES_ES[normalized]
  }
  return fallbackName
}
